import pygame
from pygame.locals import *
from module_2d import *
from rigidbody import *
from enemy import *
class Whale(Enemy):
    def __init__(self, startPos, platform,thin, rectSize, rectLocalPos):
        idle = Sprite_State(startPos,204,138,
        'asset/enemy/whale/idle/1.png',
        'asset/enemy/whale/idle/2.png',
        'asset/enemy/whale/idle/3.png',
        'asset/enemy/whale/idle/4.png',
        'asset/enemy/whale/idle/5.png',
        'asset/enemy/whale/idle/6.png',
        'asset/enemy/whale/idle/7.png',
        'asset/enemy/whale/idle/7.png',
        'asset/enemy/whale/idle/8.png',
        'asset/enemy/whale/idle/9.png',
        'asset/enemy/whale/idle/10.png',
        'asset/enemy/whale/idle/11.png',
        'asset/enemy/whale/idle/12.png',
        'asset/enemy/whale/idle/13.png',
        'asset/enemy/whale/idle/14.png',
        'asset/enemy/whale/idle/15.png',
        'asset/enemy/whale/idle/16.png',
        'asset/enemy/whale/idle/17.png',
        'asset/enemy/whale/idle/18.png',
        'asset/enemy/whale/idle/19.png',
        'asset/enemy/whale/idle/20.png',
        'asset/enemy/whale/idle/21.png',
        'asset/enemy/whale/idle/22.png',
        'asset/enemy/whale/idle/23.png',
        'asset/enemy/whale/idle/24.png',
        'asset/enemy/whale/idle/25.png',
        'asset/enemy/whale/idle/26.png',
        'asset/enemy/whale/idle/27.png',
        'asset/enemy/whale/idle/28.png',
        'asset/enemy/whale/idle/29.png',
        'asset/enemy/whale/idle/30.png',
        'asset/enemy/whale/idle/31.png',
        'asset/enemy/whale/idle/32.png',
        'asset/enemy/whale/idle/33.png',
        'asset/enemy/whale/idle/34.png',
        'asset/enemy/whale/idle/35.png',
        'asset/enemy/whale/idle/36.png',
        'asset/enemy/whale/idle/37.png',
        'asset/enemy/whale/idle/38.png',
        'asset/enemy/whale/idle/39.png',
        'asset/enemy/whale/idle/40.png',
        'asset/enemy/whale/idle/41.png',
        'asset/enemy/whale/idle/42.png',
        'asset/enemy/whale/idle/43.png',
        'asset/enemy/whale/idle/44.png')
        run = Sprite_State(startPos,204,138,
        'asset/enemy/pink_star/run/1.png',
        'asset/enemy/pink_star/run/2.png',
        'asset/enemy/pink_star/run/3.png',
        'asset/enemy/pink_star/run/4.png',
        'asset/enemy/pink_star/run/5.png',
        'asset/enemy/pink_star/run/6.png')
        hit = Sprite_State(startPos,204,138,
        'asset/enemy/whale/hit/1.png',
        'asset/enemy/whale/hit/2.png',
        'asset/enemy/whale/hit/3.png',
        'asset/enemy/whale/hit/4.png',
        'asset/enemy/whale/hit/5.png',
        'asset/enemy/whale/hit/6.png',
        'asset/enemy/whale/hit/7.png')
        super().__init__(startPos, platform,thin, rectSize, rectLocalPos, idle, hit)